name: equivariance-rl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - -e ./external/symmetrizer
    - torch
    - gymnasium[mujoco]
    - matplotlib
    - cython
    - scipy
    - stable-baselines3[extra]
    - wandb
    - emlp
    - tyro
    - jax[cuda12]
    - flax
    - optax
    - moviepy
# conda env create -f environment.yml
# conda activate equivariance-rl